### ISSUE TITLE
enumpart not recognizing networkx

### ISSUE THREAD

**Issue by hamiltonw** [alarm-redist/redist#101]
I'm running into some issues with the redist package, and I think they all stem from R isn't recognizing networkx. As an example, the code

`library(redist)
data(iowa)
dir.create("./enumerated/")
test1 <- redist.enumpart(redist.adjacency(iowa),
                        "./enumerated/iowa_output_unordered",
                        "./enumerated/iowa_output_ordered",
                        "./enumerated/iowa_output_districts",
                        ndists = 2
)`

will result in 

`Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/redist/python/ndscut.py", line 8, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
Error: './enumerated/iowa_output_districts.dat' does not exist in current working directory.`

Manually creating "./enumerated/iowa_output_districts.dat" and rerunning gives 

`Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/redist/python/ndscut.py", line 8, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'`

but now "./enumerated/iowa_output_districts.dat" is a 222x2 array. 

I've reinstalled networkx using pip, and then again within R using 

`library(reticulate)
py_install("networkx")`

but neither has worked to fix redist not recognizing networkx. Let me know if there's something I'm not doing correctly, and otherwise if there's anything else I can provide.

**Comment by hamiltonw** [comment]
Setting `init=TRUE` did the trick, thanks for the quick response.
